### ISSUE TITLE
Example TCP echo server code does not exit cleanly

### ISSUE THREAD

**Issue by hollymcr** [asyncio-docs/asyncio-doc#27] opened 2018-04-09 13:24 UTC
The example TCP echo server code does not exit cleanly from KeyboardInterrupt if a client is connected:

```
$ python3  --version
Python 3.6.3

$pip3 show asyncio
Name: asyncio
Version: 3.4.3

$ python3  echo-server.py
Serving on ('127.0.0.1', 9001)
# Connect a client but don't send anything
^C
Task was destroyed but it is pending!
task: <Task pending coro=<handle_echo() done, defined at echo-server.py:3> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fa8f396c0a8>()]>>

```
Removing the last line (loop.close()) resolves the issue, although I'm not sure why.

**Comment by vxgmichel** [comment] 2018-04-09 14:39
Hi @hollymcr,

This happens because a client is connected but it has not sent its data yet. That means the `handle_echo` task is running, waiting for the data arrive. It turns out that closing the server does not cancel the pending client tasks. Actually [it does not even track them](https://github.com/python/cpython/blob/9c463ec88ba21764f6fff8e01d6045a932a89438/Lib/asyncio/streams.py#L239):
```python
    self._loop.create_task(res)
```
I found a related issue on [bugs.python.org](https://bugs.python.org/i): [issue  28212](https://bugs.python.org/issue28212).

**Comment by hollymcr** [comment] 2018-04-09 15:07
> This happens because a client is connected but it has not sent its data yet.

To be clear, whether or not any data has been sent isn't the issue, just whether the connection is still open. In the example the connection is closed immediately after data is received but that wouldn't generally be the case in real use.

> That means the handle_echo task is running, waiting for the data arrive. It turns out that closing the server does not cancel the pending client tasks. Actually it does not even track them

Does this mean that the example is correct but the bug is in the library?

What is the implication of not calling loop.close()?

**Comment by vxgmichel** [comment] 2018-04-09 17:29
> To be clear, whether or not any data has been sent isn't the issue.

You're right, but it was the simplest way to reproduce your issue. 

Actually, it can happen even if the connection has been closed. Consider the following handler:

```python
async def handle_echo(reader, writer):
    writer.close()
    await asyncio.sleep(100)
```
> Does this mean that the example is correct but the bug is in the library?

That is my opinion yes. I just checked and the problem still appear in v3.7.0b3.

> What is the implication of not calling loop.close()?

Consider the following handler:
```python
async def handle_echo(reader, writer):
    try:
        writer.close()
        await asyncio.sleep(100)
    finally:
        print('some cleanup')
```

If you comment out `loop.close()`, `some cleanup` is never going to run.

**Comment by vstinner** [comment] 2021-05-31 07:57
I shut down the project: https://github.com/asyncio-docs/asyncio-doc/issues/33

**Closed as completed by vstinner** 2021-05-31 07:57 UTC
